src/Entity/Factura.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FacturaRepository")
 */
class Factura
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $serie;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_factura;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_emision;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $irpf;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LineaFactura", mappedBy="factura", orphanRemoval=true)
     */
    private $lineas;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\OportunidadVenta", mappedBy="factura", cascade={"persist", "remove"})
     */
    private $oportunidadVenta;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cliente", inversedBy="facturas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cliente;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Empresa", inversedBy="facturas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $empresa;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ingreso", mappedBy="factura")
     */
    private $ingresos;


    public function __construct()
    {
        $this->lineas = new ArrayCollection();
        $this->ingresos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(string $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getNumeroFactura(): ?int
    {
        return $this->numero_factura;
    }

    public function setNumeroFactura(int $numero_factura): self
    {
        $this->numero_factura = $numero_factura;

        return $this;
    }

    public function getFechaEmision(): ?\DateTimeInterface
    {
        return $this->fecha_emision;
    }

    public function setFechaEmision(\DateTimeInterface $fecha_emision): self
    {
        $this->fecha_emision = $fecha_emision;

        return $this;
    }

    public function getIrpf(): ?float
    {
        return $this->irpf;
    }

    public function setIrpf(?float $irpf): self
    {
        $this->irpf = $irpf;

        return $this;
    }

    /**
     * @return Collection|LineaFactura[]
     */
    public function getLineas(): Collection
    {
        return $this->lineas;
    }

    public function addLinea(LineaFactura $linea): self
    {
        if (!$this->lineas->contains($linea)) {
            $this->lineas[] = $linea;
            $linea->setFactura($this);
        }

        return $this;
    }

    public function removeLinea(LineaFactura $linea): self
    {
        if ($this->lineas->contains($linea)) {
            $this->lineas->removeElement($linea);
            // set the owning side to null (unless already changed)
            if ($linea->getFactura() === $this) {
                $linea->setFactura(null);
            }
        }

        return $this;
    }

    public function getOportunidadVenta(): ?OportunidadVenta
    {
        return $this->oportunidadVenta;
    }

    public function setOportunidadVenta(?OportunidadVenta $oportunidadVenta): self
    {

        if($oportunidadVenta==null && $this->oportunidadVenta != null){
          $this->oportunidadVenta->setFactura(null);
        }
        $this->oportunidadVenta = $oportunidadVenta;
        if($this->oportunidadVenta!=null){
          $this->oportunidadVenta->setFactura($this);
        }
        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }

    public function getEmpresa(): ?Empresa
    {
        return $this->empresa;
    }

    public function setEmpresa(?Empresa $empresa): self
    {
        $this->empresa = $empresa;

        return $this;
    }


    public function getSubtotal(): ?float
    {
      $subtotal = 0;
      foreach($this->getLineas() as $linea)
      {
        $subtotal+=($linea->getPrecio() * $linea->getCantidad());
      }
      return $subtotal;
    }
    public function getTotal(): ?float
    {
      $total = 0;
      foreach($this->getLineas() as $linea)
      {
        $total+=$linea->getTotal();
      }
      return $total;
    }

    public function getIVA(): ?float
    {
        $iva = 0;
        foreach($this->getLineas() as $linea)
        {
          $iva+=($linea->getIVA() * $linea->getPrecio());
        }
        return $iva;
    }

    /**
     * @return Collection|Ingreso[]
     */
    public function getIngresos(): Collection
    {
        return $this->ingresos;
    }

    public function addIngreso(Ingreso $ingreso): self
    {
        if (!$this->ingresos->contains($ingreso)) {
            $this->ingresos[] = $ingreso;
            $ingreso->setFactura($this);
        }

        return $this;
    }

    public function removeIngreso(Ingreso $ingreso): self
    {
        if ($this->ingresos->contains($ingreso)) {
            $this->ingresos->removeElement($ingreso);
            // set the owning side to null (unless already changed)
            if ($ingreso->getFactura() === $this) {
                $ingreso->setFactura(null);
            }
        }

        return $this;
    }
}

src/Controller/FiscalController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

use App\Form\EmpresaFormType;
use App\Form\ProveedorFormType;
use App\Form\FacturaFormType;
use App\Form\GastoFormType;
use App\Form\IngresoFormType;

use App\Entity\Empresa;
use App\Entity\Presupuesto;
use App\Entity\Proveedor;
use App\Entity\Ingreso;
use App\Entity\Gasto;
use App\Entity\Factura;
use App\Entity\OportunidadVenta;


//Servicios
use App\Service\PDFGenerator;
use App\Service\FacturaUtils;

/**
 * @IsGranted("ROLE_FISCAL")
 */
class FiscalController extends AbstractController
{

  /**
  * @Route("/{_locale}/empresas", name="listaempresas")
  */
  public function listaEmpresas()
  {
    $empresa_repository = $this->getDoctrine()->getRepository(Empresa::class);
    $empresas = $empresa_repository->findAll();
    return $this->render('fiscal/empresas.html.twig', array('empresas'=>$empresas));
  }

  /**
  * @Route("/{_locale}/empresa/nueva", name="nuevaempresa")
  */
  public function nuevaEmpresa(Request $request)
  {
    $msg_success=array();
    $empresa_repository = $this->getDoctrine()->getRepository(Empresa::class);
    $empresa=new Empresa();
    $form = $this->createForm(EmpresaFormType::class,$empresa);

    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($empresa);
      $entityManager->flush();
      $msg_success[]="Se ha registrado correctamente la empresa";
    }
    return $this->render('fiscal/empresanueva.html.twig', [
      "form"=>$form->createView(),
      "msg_success"=>$msg_success
    ]);

  }

  /**
  * @Route("/{_locale}/empresa/{id}", name="vereditarempresa")
  */
  public function vereditarEmpresa($id, Request $request)
  {
    $msg_success=array();
    $empresa_repository = $this->getDoctrine()->getRepository(Empresa::class);
    $empresa = $empresa_repository->findOneById($id);
    if($empresa==null)return $this->redirectToRoute("listaempresas");

    $form = $this->createForm(EmpresaFormType::class,$empresa);

    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($empresa);
      $entityManager->flush();
      $msg_success[]="Se han actualizado correctamente los datos de la empresa";
    }

    return $this->render('fiscal/empresa.html.twig', [
      "form"=>$form->createView(),
      "msg_success"=>$msg_success
    ]);
  }

  /**
  * @Route("/{_locale}/empresa/{id}/eliminar", name="eliminar_empresa")
  */
  public function eliminarEmpresa($id)
  {

    $empresaRepository = $this->getDoctrine()->getRepository(Empresa::class);
    $empresa = $empresaRepository->findOneById($id);
    if($empresa==null)
    throw $this->createNotFoundException('No exista la empresa con el id especificado');

    //No tiene presupuestos
    if($empresa->getPresupuestos()->count()>0){
      throw $this->createNotFoundException('No se puede eliminar la empresa ya que tiene presupuestos asociados. Elimine primero los presupuestos o asígnelos a otra empresa');
    }

    //No tiene facturas
    if($empresa->getFacturas()->count()>0){
      throw $this->createNotFoundException('No se puede eliminar la empresa ya que tiene facturas asociadas. Elimine primero las facturas');
    }

    //No tiene gastos
    if($empresa->getGastos()->count()>0){
      throw $this->createNotFoundException('No se puede eliminar la empresa ya que tiene gastos asociados. Elimine primero los gastos o asígnelos a otra empresa');
    }

    //TODO: No tiene ingresos

    $em = $this->getDoctrine()->getManager();
    $em->remove($empresa);
    $em->flush();
    return $this->redirectToRoute('listaempresas');


  }

  /**
  * @Route("/{_locale}/proveedores", name="lista_proveedores")
  */
  public function listaProveedores()
  {
    $prov_repository = $this->getDoctrine()->getRepository(Proveedor::class);
    $proveedores = $prov_repository->findAll();
    return $this->render('fiscal/proveedores.html.twig', array('proveedores'=>$proveedores));
  }

  /**
  * @Route("/{_locale}/proveedor/nuevo", name="nuevo_proveedor")
  */
  public function nuevoProveedor(Request $request)
  {
    $msg_success=array();
    $proveedor=new Proveedor();
    $form = $this->createForm(ProveedorFormType::class,$proveedor);

    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($proveedor);
      $entityManager->flush();
      $msg_success[]="Se ha registrado correctamente la empresa";
    }
    return $this->render('fiscal/proveedornuevo.html.twig', [
      "form"=>$form->createView(),
      "msg_success"=>$msg_success
    ]);

  }

  /**
  * @Route("/{_locale}/proveedor/{id}", name="ver_editar_proveedor")
  */
  public function vereditarProveedor($id, Request $request)
  {
    $msg_success=array();
    $prov_repository = $this->getDoctrine()->getRepository(Proveedor::class);
    $proveedor = $prov_repository->findOneById($id);
    if($proveedor==null)return $this->redirectToRoute("listaproveedores");

    $form = $this->createForm(ProveedorFormType::class,$proveedor);

    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($proveedor);
      $entityManager->flush();
      $msg_success[]="Se han actualizado correctamente los datos del proveedor";
    }

    return $this->render('fiscal/proveedor.html.twig', [
      "form"=>$form->createView(),
      "msg_success"=>$msg_success
    ]);
  }

  /**
  * @Route("/{_locale}/proveedor/{id}/eliminar", name="eliminar_proveedor")
  */
  public function eliminarProveedor($id)
  {

    $proovedorRepository = $this->getDoctrine()->getRepository(Proveedor::class);
    $proveedor = $proovedorRepository->findOneById($id);
    if($proveedor==null)
    throw $this->createNotFoundException('No existe el proveedor para el id especificado');

    //Tiene gastos
    if($proveedor->getGastos()->count()>0)
    throw $this->createNotFoundException('No se puede eliminar ya que el proveedor tiene gastos asociados');

    //eliminar
    $em = $this->getDoctrine()->getManager();
    $em->remove($proveedor);
    $em->flush();
    return $this->redirectToRoute('lista_proveedores');

  }

  /**
  * @Route("/{_locale}/gastos", name="lista_gastos")
  */
  public function listaGastos()
  {
    $gastos_repository = $this->getDoctrine()->getRepository(Gasto::class);
    $gastos = $gastos_repository->findAll();
    return $this->render('fiscal/gastos.html.twig', array('gastos'=>$gastos, 'title_h1'=>'Lista de gastos', 'nuevo_url'=>$this->generateUrl('nuevo_gasto')));
  }

  /**
  * @Route("/{_locale}/gastos/proveedor/{id}", name="lista_gastos_proveedor")
  */
  public function listaGastosProveedor($id)
  {
    $gastos_repository = $this->getDoctrine()->getRepository(Gasto::class);
    $proveedorRepository = $this->getDoctrine()->getRepository(Proveedor::class);
    $proveedor = $proveedorRepository->findOneById($id);
    if($proveedor==null)
    throw $this->createNotFoundException('No existe ningún proveedor con el id especificado');
    $gastos = $gastos_repository->findByProveedor($proveedor);
    return $this->render('fiscal/gastos.html.twig', array('gastos'=>$gastos, 'title_h1'=>'Gastos del proveedor: ' . $proveedor->getNombreComercial(), 'nuevo_url'=>$this->generateUrl('nuevo_gasto_desde_proveedor',['id'=>$proveedor->getId()])));
  }

  /**
  * @Route("/{_locale}/gastos/empresa/{id}", name="lista_gastos_empresa")
  */
  public function listaGastosEmpresa($id)
  {
    $empresaRepository = $this->getDoctrine()->getRepository(Empresa::class);
    $empresa = $empresaRepository->findOneById($id);
    if($empresa==null)
    return $this->createNotFoundException('No existe la empresa con el id especificado');
    return $this->render('fiscal/gastos.html.twig', array('gastos'=>$empresa->getGastos(), 'title_h1'=>'Gastos de la empresa: ' . $empresa->getNombreComercial(), 'nuevo_url'=>$this->generateUrl('nuevo_gasto_desde_empresa',['id'=>$empresa->getId()])));
  }

  /**
  * @Route("/{_locale}/gasto/nuevo", name="nuevo_gasto")
  */
  public function nuevoGasto(Request $request)
  {
    $msg_success=array();
    $gasto=new Gasto();
    $gasto->setFecha(new \DateTime());
    $form = $this->createForm(GastoFormType::class,$gasto);

    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($gasto);
      $entityManager->flush();
      $msg_success[]="Se ha registrado correctamente el gasto";
      return $this->redirectToRoute('lista_gastos');
    }
    return $this->render('fiscal/gastonuevo.html.twig', [
      "form"=>$form->createView(),
      "msg_success"=>$msg_success
    ]);

  }

  /**
  * @Route("/{_locale}/gasto/{id}", name="ver_editar_gasto")
  */
  public function verEditarGasto($id, Request $request)
  {
    $gastoRepository = $this->getDoctrine()->getRepository(Gasto::class);
    $gasto = $gastoRepository->findOneById($id);
    $msg_success=array();
    if($gasto==null)
      throw $this->createNotFoundException('No existe el gasto para el id especificado');

      $form = $this->createForm(GastoFormType::class,$gasto);

      $form->handleRequest($request);
      if ($form->isSubmitted() && $form->isValid()) {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($gasto);
        $entityManager->flush();
        $msg_success[]="Se ha actualizado correctamente el gasto";
      }

templates/fiscal/facturaempresa.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
  <h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-file-invoice"></i> &nbsp;{% trans %}Nueva Factura{% endtrans %}</h1>
  <hr/>


  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">{% trans %}Selecciona una Empresa{% endtrans %}</h6>
    </div>
    <div class="card-body">
      <form method="GET" action="{{action}}">
        <select class="form-control" name="id_empresa">
          {% for empresa in empresas %}
            <option value="{{empresa.id}}">{{empresa.razonsocial}}</option>
          {% endfor %}
        </select>
        <hr/>

        <input type="submit" class="btn btn-primary" value="Continuar"/>
        <a href="{{path('lista_facturas')}}" class="btn btn-danger">Cancelar</a>
      </form>
    </div>
  </div>

{% endblock %}

templates/fiscal/facturas.html.twig
{% extends 'admin.html.twig' %}
{% block stylesheets %}
{{parent()}}
  <link href="{{asset('vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
{% endblock %}
{% block javascripts %}
{{parent()}}
<script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
<script>
$("#tablaFacturas").dataTable({"order":[[ 0, "desc"]],"language":{"url":"{{asset('vendor/datatables/')}}{{ app.request.locale }}.json"}})
</script>
{% endblock %}
{% block content %}
  <h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-file-invoice"></i> &nbsp;{{title_h1}}</h1>
<hr/>
  <a href="{{nueva_url}}" class="btn btn-primary btn-icon-split mb-3">
    <span class="icon text-white-50">
      <i class="fas fa-plus"></i>
    </span>
    <span class="text">{% trans %}Añadir Nueva{% endtrans %}</span>
  </a>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">{% trans %}Facturas{% endtrans %}</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="tablaFacturas" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>{% trans %}Fecha Emisión{% endtrans %}</th>
              <th>{% trans %}Empresa{% endtrans %}</th>
              <th>{% trans %}Serie{% endtrans %}</th>
              <th>{% trans %}Número{% endtrans %}</th>
              <th>{% trans %}Cliente{% endtrans %}</th>
              <th>{% trans %}Oportunidad Venta{% endtrans %}</th>
              <th>{% trans %}Total{% endtrans %}</th>
              <th class="text-center">{% trans %}Opciones{% endtrans %}</th>
            </tr>
          </thead>
          <tbody>
            {% for factura in facturas %}
            <tr>
              <td>{{factura.fechaEmision | date('d/m/Y')}}</td>
              <td>{{factura.empresa.nombrecomercial}}</td>
              <td>{{factura.serie}}</td>
              <td>{{factura.numeroFactura}}</td>
              <td>{{factura.cliente.nombrecomercial}}</td>
              <td>
                  {% if factura.oportunidadVenta %}
                    <a href="{{path('ver_editar_oportunidad_venta',{'id':factura.oportunidadVenta.id})}}">{{factura.oportunidadVenta.nombre}}</>
                  {% else %}
                    -
                  {% endif %}
              </td>
              <td>{{factura.total | number_format(2)}} €</td>
              <td class="text-center">
                <a href="{{path("ver_factura",{"id":factura.id})}}" class="btn btn-primary btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Ver{% endtrans %}</span></a>
                <a href="{{path("ver_editar_factura",{"id":factura.id})}}" class="btn btn-warning btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-exclamation-triangle"></i></span><span class="text">{% trans %}Editar Factura{% endtrans %}</span></a>
                <a target="_blank" href="{{path("ver_factura_pdf",{"id":factura.id})}}" class="btn btn-success btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-file-pdf"></i></span><span class="text">{% trans %}PDF{% endtrans %}</span></a>

                <button data-toggle="modal" data-target="#eliminar_factura_{{factura.id}}" type="button" class="btn btn-danger btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Eliminar{% endtrans %}</span></button>
                <!-- Modal -->
                <div class="modal fade text-center" id="eliminar_factura_{{factura.id}}" tabindex="-1" role="dialog" aria-labelledby="eliminar_factura_{{factura.id}}_label" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="eliminar_factura_{{factura.id}}_label">{% trans %}Eliminar factura{% endtrans %}{{factura.serie}}/{{factura.numerofactura}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <div class="alert alert-danger">
                            <p class="text-danger">{% trans %}¿Estás seguro de que deseas eliminar la siguiente factura?{% endtrans %}</p>
                            <p class="text-danger">
                              Serie / Número: <b>{{factura.serie}}/{{factura.numeroFactura}}</b><br>
                              Cliente: <b>{{factura.cliente.nombrecomercial}}</b>
                              Empresa: <b>{{factura.empresa.nombrecomercial}}</b>
                              Importe: <b>{{factura.total}}</b>

                              <hr/>
                              {% if factura.ingresos.count %}
                              <div class="text-white p-2" style="border:2px dotted red;background:red">
                              <i class="text-white">Atención, la factura tiene ingresos asociados<hr></i>
                                  {% if factura.ingresos.count %}Ingresos asociados: {{factura.ingresos.count}}<br/>{% endif %}
                                  <i>Se eliminará la asociación a dichos ingresos si continúa, pero no se borrarán los ingresos</i>
                              </div>
                              {% endif %}

                            </p>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <a href="{{path('eliminar_factura',{'id':factura.id})}}" class="btn btn-danger"><i class="fa fa-exclamation-triangle"></i>&nbsp; {% trans %}Eliminar Factura{% endtrans %}</a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                      </div>
                    </div>
                  </div>
                </div>

              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/fiscal/gastonuevo.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
<h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-receipt"></i> &nbsp;{% trans %}Nuevo gasto{% endtrans %}</h1>
<hr/>
{% for msg in msg_success %}
<div class="alert alert-success border-bottom-success font-weight-bold"><i class="fa fa-check fa-fw"></i> &nbsp;{{msg}}</div>
{% endfor %}
<div class="card shadow p-4">

  {{ form_start(form, {attr: {class: 'user'} }) }}
  {{ form_errors(form) }}

  {{ form_widget(form) }}
  {{ form_end(form) }}

</div><!-- END: .card .shadow-->

{% endblock %}

templates/fiscal/ingresoempresa.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
  <h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-file-invoice"></i> &nbsp;{% trans %}Nueva Factura{% endtrans %}</h1>
  <hr/>


  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">{% trans %}Selecciona una Empresa{% endtrans %}</h6>
    </div>
    <div class="card-body">
      <form method="GET" action="{{action}}">
        <select class="form-control" name="id_empresa">
          {% for empresa in empresas %}
            <option value="{{empresa.id}}">{{empresa.razonsocial}}</option>
          {% endfor %}
        </select>
        <hr/>

        <input type="submit" class="btn btn-primary" value="Continuar"/>
        <a href="{{path('lista_ingresos')}}" class="btn btn-danger">Cancelar</a>
      </form>
    </div>
  </div>

{% endblock %}

templates/fiscal/ingresonuevo.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
<h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-receipt"></i> &nbsp;{% trans %}Nuevo ingreso{% endtrans %}</h1>
<hr/>
{% for msg in msg_success %}
<div class="alert alert-success border-bottom-success font-weight-bold"><i class="fa fa-check fa-fw"></i> &nbsp;{{msg}}</div>
{% endfor %}
<div class="card shadow p-4">

  {{ form_start(form, {attr: {class: 'user'} }) }}
  {{ form_errors(form) }}

  {{ form_widget(form) }}
  {{ form_end(form) }}

</div><!-- END: .card .shadow-->

{% endblock %}

templates/fiscal/vereditaringreso.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
<h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-receipt"></i> &nbsp;{% trans %}Editando ingreso{% endtrans %}</h1>
<hr/>
{% for msg in msg_success %}
<div class="alert alert-success border-bottom-success font-weight-bold"><i class="fa fa-check fa-fw"></i> &nbsp;{{msg}}</div>
{% endfor %}
<div class="card shadow p-4">

  {{ form_start(form, {attr: {class: 'user'} }) }}
  {{ form_errors(form) }}

  {{ form_widget(form) }}
  {{ form_end(form) }}

</div><!-- END: .card .shadow-->

{% endblock %}