src/Entity/Cliente.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClienteRepository")
 */
class Cliente
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=9)
     */
    private $nif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $razon_social;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_comercial;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $direccion;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $codigo_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $localidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pais;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $persona_contacto;

    /**
     * @ORM\Column(type="integer")
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $web;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comentarios;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $provincia;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_baja;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OportunidadVenta", mappedBy="cliente", orphanRemoval=true)
     */
    private $oportunidadesVentas;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Presupuesto", mappedBy="cliente", orphanRemoval=true)
     */
    private $presupuestos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Factura", mappedBy="cliente")
     */
    private $facturas;

    public function __construct()
    {
        $this->oportunidadesVentas = new ArrayCollection();
        $this->presupuestos = new ArrayCollection();
        $this->facturas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNif(): ?string
    {
        return $this->nif;
    }

    public function setNif(string $nif): self
    {
        $this->nif = $nif;

        return $this;
    }

    public function getRazonSocial(): ?string
    {
        return $this->razon_social;
    }

    public function setRazonSocial(string $razon_social): self
    {
        $this->razon_social = $razon_social;

        return $this;
    }

    public function getNombreComercial(): ?string
    {
        return $this->nombre_comercial;
    }

    public function setNombreComercial(string $nombre_comercial): self
    {
        $this->nombre_comercial = $nombre_comercial;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getCodigoPostal(): ?string
    {
        return $this->codigo_postal;
    }

    public function setCodigoPostal(string $codigo_postal): self
    {
        $this->codigo_postal = $codigo_postal;

        return $this;
    }

    public function getLocalidad(): ?string
    {
        return $this->localidad;
    }

    public function setLocalidad(string $localidad): self
    {
        $this->localidad = $localidad;

        return $this;
    }

    public function getPais(): ?string
    {
        return $this->pais;
    }

    public function setPais(string $pais): self
    {
        $this->pais = $pais;

        return $this;
    }

    public function getPersonaContacto(): ?string
    {
        return $this->persona_contacto;
    }

    public function setPersonaContacto(?string $persona_contacto): self
    {
        $this->persona_contacto = $persona_contacto;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(int $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function setWeb(?string $web): self
    {
        $this->web = $web;

        return $this;
    }

    public function getComentarios(): ?string
    {
        return $this->comentarios;
    }

    public function setComentarios(?string $comentarios): self
    {
        $this->comentarios = $comentarios;

        return $this;
    }

    public function getProvincia(): ?string
    {
        return $this->provincia;
    }

    public function setProvincia(string $provincia): self
    {
        $this->provincia = $provincia;

        return $this;
    }

    public function getFechaBaja(): ?\DateTimeInterface
    {
        return $this->fecha_baja;
    }

    public function setFechaBaja(?\DateTimeInterface $fecha_baja): self
    {
        $this->fecha_baja = $fecha_baja;

        return $this;
    }

    /**
     * @return Collection|OportunidadVenta[]
     */
    public function getOportunidadesVentas(): Collection
    {
        return $this->oportunidadesVentas;
    }

    public function addOportunidadesVenta(OportunidadVenta $oportunidadesVenta): self
    {
        if (!$this->oportunidadesVentas->contains($oportunidadesVenta)) {
            $this->oportunidadesVentas[] = $oportunidadesVenta;
            $oportunidadesVenta->setCliente($this);
        }

        return $this;
    }

    public function removeOportunidadesVenta(OportunidadVenta $oportunidadesVenta): self
    {
        if ($this->oportunidadesVentas->contains($oportunidadesVenta)) {
            $this->oportunidadesVentas->removeElement($oportunidadesVenta);
            // set the owning side to null (unless already changed)
            if ($oportunidadesVenta->getCliente() === $this) {
                $oportunidadesVenta->setCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Presupuesto[]
     */
    public function getPresupuestos(): Collection
    {
        return $this->presupuestos;
    }

    public function addPresupuesto(Presupuesto $presupuesto): self
    {
        if (!$this->presupuestos->contains($presupuesto)) {
            $this->presupuestos[] = $presupuesto;
            $presupuesto->setCliente($this);
        }

        return $this;
    }

    public function removePresupuesto(Presupuesto $presupuesto): self
    {
        if ($this->presupuestos->contains($presupuesto)) {
            $this->presupuestos->removeElement($presupuesto);
            // set the owning side to null (unless already changed)
            if ($presupuesto->getCliente() === $this) {
                $presupuesto->setCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Factura[]
     */
    public function getFacturas(): Collection
    {
        return $this->facturas;
    }

    public function addFactura(Factura $factura): self
    {
        if (!$this->facturas->contains($factura)) {
            $this->facturas[] = $factura;
            $factura->setCliente($this);
        }

        return $this;
    }

    public function removeFactura(Factura $factura): self
    {
        if ($this->facturas->contains($factura)) {
            $this->facturas->removeElement($factura);
            // set the owning side to null (unless already changed)
            if ($factura->getCliente() === $this) {
                $factura->setCliente(null);
            }
        }

        return $this;
    }
}

src/Entity/Factura.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FacturaRepository")
 */
class Factura
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $serie;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_factura;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_emision;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $irpf;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LineaFactura", mappedBy="factura", orphanRemoval=true)
     */
    private $lineas;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\OportunidadVenta", mappedBy="factura", cascade={"persist", "remove"})
     */
    private $oportunidadVenta;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cliente", inversedBy="facturas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cliente;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Empresa", inversedBy="facturas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $empresa;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ingreso", mappedBy="factura")
     */
    private $ingresos;


    public function __construct()
    {
        $this->lineas = new ArrayCollection();
        $this->ingresos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(string $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getNumeroFactura(): ?int
    {
        return $this->numero_factura;
    }

    public function setNumeroFactura(int $numero_factura): self
    {
        $this->numero_factura = $numero_factura;

        return $this;
    }

    public function getFechaEmision(): ?\DateTimeInterface
    {
        return $this->fecha_emision;
    }

    public function setFechaEmision(\DateTimeInterface $fecha_emision): self
    {
        $this->fecha_emision = $fecha_emision;

        return $this;
    }

    public function getIrpf(): ?float
    {
        return $this->irpf;
    }

    public function setIrpf(?float $irpf): self
    {
        $this->irpf = $irpf;

        return $this;
    }

    /**
     * @return Collection|LineaFactura[]
     */
    public function getLineas(): Collection
    {
        return $this->lineas;
    }

    public function addLinea(LineaFactura $linea): self
    {
        if (!$this->lineas->contains($linea)) {
            $this->lineas[] = $linea;
            $linea->setFactura($this);
        }

        return $this;
    }

    public function removeLinea(LineaFactura $linea): self
    {
        if ($this->lineas->contains($linea)) {
            $this->lineas->removeElement($linea);
            // set the owning side to null (unless already changed)
            if ($linea->getFactura() === $this) {
                $linea->setFactura(null);
            }
        }

        return $this;
    }

    public function getOportunidadVenta(): ?OportunidadVenta
    {
        return $this->oportunidadVenta;
    }

    public function setOportunidadVenta(?OportunidadVenta $oportunidadVenta): self
    {

        if($oportunidadVenta==null && $this->oportunidadVenta != null){
          $this->oportunidadVenta->setFactura(null);
        }
        $this->oportunidadVenta = $oportunidadVenta;
        if($this->oportunidadVenta!=null){
          $this->oportunidadVenta->setFactura($this);
        }
        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }

    public function getEmpresa(): ?Empresa
    {
        return $this->empresa;
    }

    public function setEmpresa(?Empresa $empresa): self
    {
        $this->empresa = $empresa;

        return $this;
    }


    public function getSubtotal(): ?float
    {
      $subtotal = 0;
      foreach($this->getLineas() as $linea)
      {
        $subtotal+=($linea->getPrecio() * $linea->getCantidad());
      }
      return $subtotal;
    }
    public function getTotal(): ?float
    {
      $total = 0;
      foreach($this->getLineas() as $linea)
      {
        $total+=$linea->getTotal();
      }
      return $total;
    }

    public function getIVA(): ?float
    {
        $iva = 0;
        foreach($this->getLineas() as $linea)
        {
          $iva+=($linea->getIVA() * $linea->getPrecio());
        }
        return $iva;
    }

    /**
     * @return Collection|Ingreso[]
     */
    public function getIngresos(): Collection
    {
        return $this->ingresos;
    }

    public function addIngreso(Ingreso $ingreso): self
    {
        if (!$this->ingresos->contains($ingreso)) {
            $this->ingresos[] = $ingreso;
            $ingreso->setFactura($this);
        }

        return $this;
    }

    public function removeIngreso(Ingreso $ingreso): self
    {
        if ($this->ingresos->contains($ingreso)) {
            $this->ingresos->removeElement($ingreso);
            // set the owning side to null (unless already changed)
            if ($ingreso->getFactura() === $this) {
                $ingreso->setFactura(null);
            }
        }

        return $this;
    }
}

templates/crm/oportunidades.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
<h1 class="h3 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-columns"></i> &nbsp;{{title}}</h1>
<hr/>
<div class="row">
  <div class="col-md-12">
    <div class="row">
      {% if not oportunidades %}
        <div class="col-md-12">
          <div class="alert alert-danger">
              <p class="text-danger">{% trans %}No existen oportunidades de venta{% endtrans %}</p>
          </div>
        </div>
      {% endif %}
    {% for oportunidad in oportunidades %}
      <div class="col-md-12 col-lg-6">
      <div class="card text-gray-800 mt-4">
        <div class="card-header bg-primary text-white">
          <b>{{oportunidad.nombre}}</b>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <b class="d-block">Estado:</b>
              {% if oportunidad.perdida  %}<span class="text-danger"><i class="fa fa-thumbs-down"></i> Perdida</span>
              {% elseif oportunidad.ganada %}<span class="text-success"><i class="fa fa-thumbs-up"></i> Ganada</span>
              {% elseif oportunidad.columnakanban%}<span class="text-info"><i class="fa fa-asterisk"></i> En Panel Kanban (<b>{{oportunidad.columnakanban.nombre}}</b>)</span>
              {% else %}<span class="text-warning"><i class="fa fa-exclamation-triangle"></i> Sin asignar</span>
              {% endif %}
            </div>
            <div class="col-md-3"><b class="d-block">Fecha:</b>{{oportunidad.fechaCreacion | date('d/M/Y')}}</div>
            <div class="col-md-3"><b class="d-block">Ingreso Estimado:</b>{{oportunidad.ingresoEstimado | number_format(2)}} €</div>
            <div class="col-md-3"><b class="d-block">Porcentaje Estimado:</b>{{oportunidad.porcentajeExitoEstimado*100 | number_format(2)}} %</div>
          </div>
          <div class="row mt-3">
            <div class="col-md-6"><b class="d-block">Responsable:</b>{{oportunidad.responsable.email}}</div>
            <div class="col-md-6"><b class="d-block">Cliente:</b>{{oportunidad.cliente.nombreComercial}}</div>
          </div>
          <div class="row mt-3">
            <div class="col-md-6"><b class="d-block">Descripcion</b>{{oportunidad.descripcion}}</div>

          </div>

          <div class="row mt-3">
            {% if oportunidad.perdida %}
              <div class="alert alert-danger col-md-12"><b class="d-block">Motivo pérdida</b>{{oportunidad.motivoperdida}}</div>
            {% endif %}
          </div>
          <hr>
          {% if oportunidad.presupuesto %}
          <a href="{{path("ver_editar_presupuesto",{"id":oportunidad.presupuesto.id})}}" class="btn btn-info btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Ver Presupuesto{% endtrans %}</span></a>
          {% else %}
          <a href="{{path('nuevo_presupuesto')}}?id_oportunidad={{oportunidad.id}}" class="btn btn-primary btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-plus"></i></span><span class="text">{% trans %}Crear Presupuesto{% endtrans %}</span></a>
          {% endif %}

          {% if oportunidad.factura %}
          <a href="{{path("ver_factura",{"id":oportunidad.factura.id})}}" class="btn btn-info btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Ver Factura{% endtrans %}</span></a>
          {% else %}
          <a href="{{path("nueva_factura_desde_oportunidad",{"id":oportunidad.id})}}" class="btn btn-primary btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-plus"></i></span><span class="text">{% trans %}Nueva Factura{% endtrans %}</span></a>
          {% endif %}


        </div>

        <div class="card-footer text-right bg-gray-200">

          <a href="{{path('ver_editar_oportunidad_venta',{'id':oportunidad.id})}}" class="btn btn-info btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-edit"></i></span><span class="text">{% trans %}Editar{% endtrans %}</span></a>
          <button data-toggle="modal" data-target="#eliminar_oportunidad_{{oportunidad.id}}" type="button" class="btn btn-danger btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Eliminar{% endtrans %}</span></button>
          <!-- Modal -->
          <div class="modal fade text-center" id="eliminar_oportunidad_{{oportunidad.id}}" tabindex="-1" role="dialog" aria-labelledby="eliminar_oportunidad_{{oportunidad.id}}_label" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="eliminar_oportunidad_{{oportunidad.id}}_label">Eliminar oportunidad {{oportunidad.nombre}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="alert alert-danger">
                      <p class="text-danger">¿Estás seguro de que deseas eliminar el siguiente cliente?</p>
                      <p class="text-danger">
                        Nombre: <b>{{oportunidad.nombre}}</b><br>
                        Descripcion: <b>{{oportunidad.descripcion}}</b>
                      </p>
                  </div>
                </div>
                <div class="modal-footer">
                  <a href="{{path('eliminar_oportunidad_venta',{'id':oportunidad.id})}}" class="btn btn-danger"><i class="fa fa-exclamation-triangle"></i>&nbsp; Eliminar Oportunidad</a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
              </div>
            </div>
          </div>


        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  </div>
</div>

{% endblock %}

templates/crm/presupuestos.html.twig
{% extends 'admin.html.twig' %}
{% block stylesheets %}
{{parent()}}
  <link href="{{asset('vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
{% endblock %}
{% block javascripts %}
{{parent()}}
<script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
<script>
$("#tablaPresupuestos").dataTable({"order":[[ 0, "desc"]],"language":{"url":"{{asset('vendor/datatables/')}}{{ app.request.locale }}.json"}})
</script>
{% endblock %}
{% block content %}
  <h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-user-tie"></i> &nbsp;{% trans %}Lista de presupuestos{% endtrans %}</h1>
<hr/>
  <a href="{{path('nuevo_presupuesto')}}" class="btn btn-primary btn-icon-split mb-3">
    <span class="icon text-white-50">
      <i class="fas fa-plus"></i>
    </span>
    <span class="text">{% trans %}Añadir Nuevo{% endtrans %}</span>
  </a>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">{% trans %}Presupuestos{% endtrans %}</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="tablaPresupuestos" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>{% trans %}Fecha Emisión{% endtrans %}</th>
              <th>{% trans %}Número{% endtrans %}</th>
              <th>{% trans %}Cliente{% endtrans %}</th>
              <th>{% trans %}Dias validez{% endtrans %}</th>
              <th>{% trans %}Oportunidad Venta{% endtrans %}</th>
              <th>{% trans %}Total{% endtrans %}</th>
              <th class="text-center">{% trans %}Opciones{% endtrans %}</th>
            </tr>
          </thead>
          <tbody>
            {% for presupuesto in presupuestos %}
            <tr>
              <td>{{presupuesto.fechaEmision | date('d/m/Y')}}</td>
              <td>{{presupuesto.numeroPresupuesto}}</td>
              <td>{{presupuesto.cliente.nombrecomercial}}</td>
              <td>{{presupuesto.diasValidez}}</td>
              <td>
                  {% if presupuesto.oportunidadVenta %}
                    <a href="{{path('ver_editar_oportunidad_venta',{'id':presupuesto.oportunidadVenta.id})}}">{{presupuesto.oportunidadVenta.nombre}}</a>
                  {% else %}
                  -
                  {% endif %}
              </td>
              <td>{{presupuesto.total | number_format(2)}} €</td>
              <td class="text-center">
                <a href="{{path("ver_editar_presupuesto",{"id":presupuesto.id})}}" class="btn btn-primary btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Ver{% endtrans %}</span></a>
                <a target="_blank" href="{{path("ver_presupuesto_pdf",{"id":presupuesto.id})}}" class="btn btn-success btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-file-pdf"></i></span><span class="text">{% trans %}PDF{% endtrans %}</span></a>
                <a href="{{path("nueva_factura_desde_presupuesto",{"id":presupuesto.id})}}" class="btn btn-info btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-file-invoice"></i></span><span class="text">{% trans %}Crear Factura{% endtrans %}</span></a>
                <button data-toggle="modal" data-target="#eliminar_presupuesto_{{presupuesto.id}}" type="button" class="btn btn-danger btn-icon-split btn-sm"><span class="icon text-white"><i class="fas fa-fw fa-eye"></i></span><span class="text">{% trans %}Eliminar{% endtrans %}</span></button>
                <!-- Modal -->
                <div class="modal fade text-center" id="eliminar_presupuesto_{{presupuesto.id}}" tabindex="-1" role="dialog" aria-labelledby="eliminar_presupuesto_{{presupuesto.id}}_label" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="eliminar_presupuesto_{{presupuesto.id}}_label">Eliminar presupuesto {{presupuesto.numeropresupuesto}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <div class="alert alert-danger">
                            <p class="text-danger">¿Estás seguro de que deseas eliminar el siguiente presupuesto?</p>
                            <p class="text-danger">
                              Número: <b>{{presupuesto.numeropresupuesto}}</b><br>
                              Cliente: <b>{{presupuesto.cliente.nombrecomercial}}</b><br>
                              Importe: <b>{{presupuesto.total}}€</b>
                            </p>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <a href="{{path('eliminar_presupuesto',{'id':presupuesto.id})}}" class="btn btn-danger"><i class="fa fa-exclamation-triangle"></i>&nbsp; Eliminar Presupuesto</a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                      </div>
                    </div>
                  </div>
                </div>


              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/crm/vereditarcolumnakanban.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
<h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-columns"></i> &nbsp;{% trans %}Ver / Editar Columna Kanban{% endtrans %}</h1>
<div class="row">
  <div class="col-md-12">
    {% if smessage %}
    <div class="alert alert-success text-success"><b>{{smessage}}</b></div>
    {% endif %}
    <div class="mt-2 card p-4">
      {{form(form)}}
    </div>
  </div>
</div>
{% endblock %}

templates/crm/vereditaroportunidadventa.html.twig
{% extends 'admin.html.twig' %}
{% block content %}
<h1 class="h1 mb-2 font-weight-bold text-gray-800"><i class="fas fa-fw fa-columns"></i> &nbsp;{% trans %}Ver / Editar Oportunidad de Venta{% endtrans %}</h1>
<div class="row">
  <div class="col-md-12">
    <div class="mt-2 card p-4">
      {{form(form)}}
    </div>
  </div>
</div>
{% endblock %}